export const foodEmojiMap: { [key: string]: string } = {
  // Cereais e derivados
  "Arroz, integral, cozido": "🍚",
  "Arroz, integral, cru": "🍚",
  "Arroz, tipo 1, cozido": "🍚",
  "Arroz, tipo 1, cru": "🍚",
  "Arroz, tipo 2, cozido": "🍚",
  "Arroz, tipo 2, cru": "🍚",
  "Aveia, flocos, crua": "🌾",
  "Biscoito, doce, maisena": "🍪",
  "Biscoito, doce, recheado com chocolate": "🍪",
  "Biscoito, doce, recheado com morango": "🍪",
  "Biscoito, doce, wafer, recheado de chocolate": "🍪",
  "Biscoito, doce, wafer, recheado de morango": "🍪",
  "Biscoito, salgado, cream cracker": "🍪",
  "Bolo, mistura para": "🍰",
  "Bolo, pronto, aipim": "🍰",
  "Bolo, pronto, chocolate": "🍰",
  "Bolo, pronto, coco": "🍰",
  "Bolo, pronto, milho": "🍰",
  "Canjica, branca, crua": "🌽",
  "Canjica, com leite integral": "🌽",
  "Cereais, milho, flocos, com sal": "🌽",
  "Cereais, milho, flocos, sem sal": "🌽",
  "Cereais, mingau, milho, infantil": "🥣",
  "Cereais, mistura para vitamina, trigo, cevada e aveia": "🌾",
  "Cereal matinal, milho": "🥣",
  "Cereal matinal, milho, açúcar": "🥣",
  "Creme de arroz, pó": "🍚",
  "Creme de milho, pó": "🌽",
  "Curau, milho verde": "🌽",
  "Curau, milho verde, mistura para": "🌽",
  "Farinha, de arroz, enriquecida": "🌾",
  "Farinha, de centeio, integral": "🌾",
  "Farinha, de milho, amarela": "🌽",
  "Farinha, de rosca": "🌾",
  "Farinha, de trigo": "🌾",
  "Farinha, láctea, de cereais": "🥛",
  "Lasanha, massa fresca, cozida": "🍝",
  "Lasanha, massa fresca, crua": "🍝",
  "Macarrão, instantâneo": "🍝",
  "Macarrão, trigo, cru": "🍝",
  "Macarrão, trigo, cru, com ovos": "🍝",
  "Milho, amido, cru": "🌽",
  "Milho, fubá, cru": "🌽",
  "Milho, verde, cru": "🌽",
  "Milho, verde, enlatado, drenado": "🌽",
  "Mingau tradicional, pó": "🥣",
  "Pamonha, barra para cozimento, pré-cozida": "🌽",
  "Pão, aveia, forma": "🍞",
  "Pão, de soja": "🍞",
  "Pão, glúten, forma": "🍞",
  "Pão, milho, forma": "🍞",
  "Pão, trigo, forma, integral": "🍞",
  "Pão, trigo, francês": "🥖",
  "Pão, trigo, sovado": "🍞",
  "Pastel, de carne, cru": "🥟",
  "Pastel, de carne, frito": "🥟",
  "Pastel, de queijo, cru": "🥟",
  "Pastel, de queijo, frito": "🥟",
  "Pastel, massa, crua": "🥟",
  "Pastel, massa, frita": "🥟",
  "Pipoca, com óleo de soja, sem sal": "🍿",
  "Polenta, pré-cozida": "🌽",
  "Torrada, pão francês": "🍞",

  // Verduras, hortaliças e derivados
  "Abóbora, cabotian, cozida": "🎃",
  "Abóbora, cabotian, crua": "🎃",
  "Abóbora, menina brasileira, crua": "🎃",
  "Abóbora, moranga, crua": "🎃",
  "Abóbora, moranga, refogada": "🎃",
  "Abóbora, pescoço, crua": "🎃",
  "Abobrinha, italiana, cozida": "🥒",
  "Abobrinha, italiana, crua": "🥒",
  "Abobrinha, italiana, refogada": "🥒",
  "Abobrinha, paulista, crua": "🥒",
  "Acelga, crua": "🥬",
  "Agrião, cru": "🥬",
  "Aipo, cru": "🥬",
  "Alface, americana, crua": "🥬",
  "Alface, crespa, crua": "🥬",
  "Alface, lisa, crua": "🥬",
  "Alface, roxa, crua": "🥬",
  "Alfavaca, crua": "🥬",
  "Alho, cru": "🧄",
  "Alho-poró, cru": "🧄",
  "Almeirão, cru": "🥬",
  "Almeirão, refogado": "🥬",
  "Batata, baroa, cozida": "🥔",
  "Batata, baroa, crua": "🥔",
  "Batata, doce, cozida": "🥔",
  "Batata, doce, crua": "🥔",
  "Batata, frita, tipo chips, industrializada": "🍟",
  "Batata, inglesa, cozida": "🥔",
  "Batata, inglesa, crua": "🥔",
  "Batata, inglesa, frita": "🍟",
  "Batata, inglesa, sauté": "🥔",
  "Berinjela, cozida": "🍆",
  "Berinjela, crua": "🍆",
  "Beterraba, cozida": "🫑",
  "Beterraba, crua": "🫑",
  "Brócolis, cozido": "🥦",
  "Brócolis, cru": "🥦",
  "Cará, cozido": "🥔",
  "Cará, cru": "🥔",
  "Caruru, cru": "🥬",
  "Catalonha, crua": "🥬",
  "Catalonha, refogada": "🥬",
  "Cebola, crua": "🧅",
  "Cebolinha, crua": "🧅",
  "Cenoura, cozida": "🥕",
  "Cenoura, crua": "🥕",
  "Chicória, crua": "🥬",
  "Chuchu, cozido": "🥒",
  "Chuchu, cru": "🥒",
  "Coentro, folhas desidratadas": "🌿",
  "Couve, manteiga, crua": "🥬",
  "Couve, manteiga, refogada": "🥬",
  "Couve-flor, crua": "🥦",
  "Couve-flor, cozida": "🥦",
  "Espinafre, Nova Zelândia, cru": "🥬",
  "Espinafre, Nova Zelândia, refogado": "🥬",
  "Farinha, de mandioca, crua": "🌾",
  "Farinha, de mandioca, torrada": "🌾",
  "Farinha, de puba": "🌾",
  "Fécula, de mandioca": "🌾",
  "Feijão, broto, cru": "🫘",
  "Inhame, cru": "🥔",
  "Jiló, cru": "🍆",
  "Jurubeba, crua": "🥬",
  "Mandioca, cozida": "🥔",
  "Mandioca, crua": "🥔",
  "Mandioca, farofa, temperada": "🌾",
  "Mandioca, frita": "🍟",
  "Manjericão, cru": "🌿",
  "Maxixe, cru": "🥒",
  "Mostarda, folha, crua": "🥬",
  "Nhoque, batata, cozido": "🥔",
  "Nabo, cru": "🥕",
  "Palmito, juçara, em conserva": "🌱",
  "Palmito, pupunha, em conserva": "🌱",
  "Pão, de queijo, assado": "🧀",
  "Pão, de queijo, cru": "🧀",
  "Pepino, cru": "🥒",
  "Pimentão, amarelo, cru": "🫑",
  "Pimentão, verde, cru": "🫑",
  "Pimentão, vermelho, cru": "🫑",
  "Polvilho, doce": "🌾",
  "Quiabo, cru": "🥬",
  "Rabanete, cru": "🥕",
  "Repolho, branco, cru": "🥬",
  "Repolho, roxo, cru": "🥬",
  "Repolho, roxo, refogado": "🥬",
  "Rúcula, crua": "🥬",
  "Salsa, crua": "🌿",
  "Seleta de legumes, enlatada": "🥗",
  "Serralha, crua": "🥬",
  "Taioba, crua": "🥬",
  "Tomate, com semente, cru": "🍅",
  "Tomate, extrato": "🍅",
  "Tomate, molho industrializado": "🍅",
  "Tomate, purê": "🍅",
  "Tomate, salada": "🍅",
  "Vagem, crua": "🥬",

  // Frutas e derivados
  "Abacate, cru": "🥑",
  "Abacaxi, cru": "🍍",
  "Abacaxi, polpa, congelada": "🍍",
  "Abiu, cru": "🍈",
  "Açaí, polpa, com xarope de guaraná e glucose": "🫐",
  "Açaí, polpa, congelada": "🫐",
  "Acerola, crua": "🍒",
  "Acerola, polpa, congelada": "🍒",
  "Ameixa, calda, enlatada": "🫐",
  "Ameixa, crua": "🫐",
  "Ameixa, em calda, enlatada, drenada": "🫐",
  "Atemóia, crua": "🍈",
  "Banana, da terra, crua": "🍌",
  "Banana, doce em barra": "🍌",
  "Banana, figo, crua": "🍌",
  "Banana, maçã, crua": "🍌",
  "Banana, nanica, crua": "🍌",
  "Banana, ouro, crua": "🍌",
  "Banana, pacova, crua": "🍌",
  "Banana, prata, crua": "🍌",
  "Cacau, cru": "🍫",
  "Cajá-Manga, cru": "🥭",
  "Cajá, polpa, congelada": "🥭",
  "Caju, cru": "🥭",
  "Caju, polpa, congelada": "🥭",
  "Caju, suco concentrado, envasado": "🥭",
  "Caqui, chocolate, cru": "🍅",
  "Carambola, crua": "⭐",
  "Ciriguela, crua": "🍈",
  "Cupuaçu, cru": "🍈",
  "Cupuaçu, polpa, congelada": "🍈",
  "Figo, cru": "🍈",
  "Figo, enlatado, em calda": "🍈",
  "Fruta-pão, crua": "🍞",
  "Goiaba, branca, com casca, crua": "🍈",
  "Goiaba, doce em pasta": "🍈",
  "Goiaba, doce, cascão": "🍈",
  "Goiaba, vermelha, com casca, crua": "🍈",
  "Graviola, crua": "🍈",
  "Graviola, polpa, congelada": "🍈",
  "Jabuticaba, crua": "🍇",
  "Jaca, crua": "🍈",
  "Jambo, cru": "🍈",
  "Jamelão, cru": "🍇",
  "Kiwi, cru": "🥝",
  "Laranja, baía, crua": "🍊",
  "Laranja, baía, suco": "🧃",
  "Laranja, da terra, crua": "🍊",
  "Laranja, da terra, suco": "🧃",
  "Laranja, lima, crua": "🍊",
  "Laranja, lima, suco": "🧃",
  "Laranja, pêra, crua": "🍊",
  "Laranja, pêra, suco": "🧃",
  "Laranja, valência, crua": "🍊",
  "Laranja, valência, suco": "🧃",
  "Limão, cravo, suco": "🧃",
  "Limão, galego, suco": "🧃",
  "Limão, tahiti, cru": "🍋",
  "Maçã, Argentina, com casca, crua": "🍎",
  "Maçã, Fuji, com casca, crua": "🍎",
  "Macaúba, crua": "🥥",
  "Mamão, doce em calda, drenado": "🥭",
  "Mamão, Formosa, cru": "🥭",
  "Mamão, Papaia, cru": "🥭",
  "Mamão verde, doce em calda, drenado": "🥭",
  "Manga, Haden, crua": "🥭",
  "Manga, Palmer, crua": "🥭",
  "Manga, polpa, congelada": "🥭",
  "Manga, Tommy Atkins, crua": "🥭",
  "Maracujá, cru": "🥭",
  "Maracujá, polpa, congelada": "🥭",
  "Maracujá, suco concentrado, envasado": "🧃",
  "Melancia, crua": "🍉",
  "Melão, cru": "🍈",
  "Mexerica, Murcote, crua": "🍊",
  "Mexerica, Rio, crua": "🍊",
  "Morango, cru": "🍓",
  "Nêspera, crua": "🍈",
  "Pequi, cru": "🥭",
  "Pêra, Park, crua": "🍐",
  "Pêra, Williams, crua": "🍐",
  "Pêssego, Aurora, cru": "🍑",
  "Pêssego, enlatado, em calda": "🍑",
  "Pinha, crua": "🍈",
  "Pitanga, crua": "🍒",
  "Pitanga, polpa, congelada": "🍒",
  "Romã, crua": "🍈",
  "Tamarindo, cru": "🍈",
  "Tangerina, Poncã, crua": "🍊",
  "Tangerina, Poncã, suco": "🧃",
  "Tucumã, cru": "🥥",
  "Umbu, cru": "🍈",
  "Umbu, polpa, congelada": "🍈",
  "Uva, Itália, crua": "🍇",
  "Uva, Rubi, crua": "🍇",
  "Uva, suco concentrado, envasado": "🧃",

  // Gorduras e óleos
  "Azeite, de dendê": "🫒",
  "Azeite, de oliva, extra virgem": "🫒",
  "Manteiga, com sal": "🧈",
  "Manteiga, sem sal": "🧈",
  "Margarina, com óleo hidrogenado, com sal (65% de lipídeos)": "🧈",
  "Margarina, com óleo hidrogenado, sem sal (80% de lipídeos)": "🧈",
  "Margarina, com óleo interesterificado, com sal (65%de lipídeos)": "🧈",
  "Margarina, com óleo interesterificado, sem sal (65% de lipídeos)": "🧈",
  "Óleo, de babaçu": "🫒",
  "Óleo, de canola": "🫒",
  "Óleo, de girassol": "🫒",
  "Óleo, de milho": "🫒",
  "Óleo, de pequi": "🫒",
  "Óleo, de soja": "🫒",

  // Pescados e frutos do mar
  "Abadejo, filé, congelado, assado": "🐟",
  "Abadejo, filé, congelado,cozido": "🐟",
  "Abadejo, filé, congelado, cru": "🐟",
  "Abadejo, filé, congelado, grelhado": "🐟",
  "Atum, conserva em óleo": "🐟",
  "Atum, fresco, cru": "🐟",
  "Bacalhau, salgado, cru": "🐟",
  "Bacalhau, salgado, refogado": "🐟",
  "Cação, posta, com farinha de trigo, frita": "🐟",
  "Cação, posta, cozida": "🐟",
  "Cação, posta, crua": "🐟",
  "Camarão, Rio Grande, grande, cozido": "🦐",
  "Camarão, Rio Grande, grande, cru": "🦐",
  "Camarão, Sete Barbas, sem cabeça, com casca, frito": "🦐",
  "Caranguejo, cozido": "🦀",
  "Corimba, cru": "🐟",
  "Corimbatá, assado": "🐟",
  "Corimbatá, cozido": "🐟",
  "Corvina de água doce, crua": "🐟",
  "Corvina do mar, crua": "🐟",
  "Corvina grande, assada": "🐟",
  "Corvina grande, cozida": "🐟",
  "Dourada de água doce, fresca": "🐟",
  "Lambari, congelado, cru": "🐟",
  "Lambari, congelado, frito": "🐟",
  "Lambari, fresco, cru": "🐟",
  "Manjuba, com farinha de trigo, frita": "🐟",
  "Manjuba, frita": "🐟",
  "Merluza, filé, assado": "🐟",
  "Merluza, filé, cru": "🐟",
  "Merluza, filé, frito": "🐟",
  "Pescada, branca, crua": "🐟",
  "Pescada, branca, frita": "🐟",
  "Pescada, filé, com farinha de trigo, frito": "🐟",
  "Pescada, filé, cru": "🐟",
  "Pescada, filé, frito": "🐟",
  "Pescada, filé, molho escabeche": "🐟",
  "Pescadinha, crua": "🐟",
  "Pintado, assado": "🐟",
  "Pintado, cru": "🐟",
  "Pintado, grelhado": "🐟",
  "Porquinho, cru": "🐟",
  "Salmão, filé, com pele, fresco,  grelhado": "🐟",
  "Salmão, sem pele, fresco, cru": "🐟",
  "Salmão, sem pele, fresco, grelhado": "🐟",
  "Sardinha, assada": "🐟",
  "Sardinha, conserva em óleo": "🐟",
  "Sardinha, frita": "🐟",
  "Sardinha, inteira, crua": "🐟",
  "Tucunaré, filé, congelado, cru": "🐟",

  // Carnes e derivados
  "Apresuntado": "🥓",
  "Caldo de carne, tablete": "🥩",
  "Caldo de galinha, tablete": "🍗",
  "Carne, bovina, acém, moído, cozido": "🥩",
  "Carne, bovina, acém, moído, cru": "🥩",
  "Carne, bovina, acém, sem gordura, cozido": "🥩",
  "Carne, bovina, acém, sem gordura, cru": "🥩",
  "Carne, bovina, almôndegas, cruas": "🥩",
  "Carne, bovina, almôndegas, fritas": "🥩",
  "Carne, bovina, bucho, cozido": "🥩",
  "Carne, bovina, bucho, cru": "🥩",
  "Carne, bovina, capa de contra-filé, com gordura, crua": "🥩",
  "Carne, bovina, capa de contra-filé, com gordura, grelhada": "🥩",
  "Carne, bovina, capa de contra-filé, sem gordura, crua": "🥩",
  "Carne, bovina, capa de contra-filé, sem gordura, grelhada": "🥩",
  "Carne, bovina, charque, cozido": "🥩",
  "Carne, bovina, charque, cru": "🥩",
  "Carne, bovina, contra-filé, à milanesa": "🥩",
  "Carne, bovina, contra-filé de costela, cru": "🥩",
  "Carne, bovina, contra-filé de costela, grelhado": "🥩",
  "Carne, bovina, contra-filé, com gordura, cru": "🥩",
  "Carne, bovina, contra-filé, com gordura, grelhado": "🥩",
  "Carne, bovina, contra-filé, sem gordura, cru": "🥩",
  "Carne, bovina, contra-filé, sem gordura, grelhado": "🥩",
  "Carne, bovina, costela, assada": "🥩",
  "Carne, bovina, costela, crua": "🥩",
  "Carne, bovina, coxão duro, sem gordura, cozido": "🥩",
  "Carne, bovina, coxão duro, sem gordura, cru": "🥩",
  "Carne, bovina, coxão mole, sem gordura, cozido": "🥩",
  "Carne, bovina, coxão mole, sem gordura, cru": "🥩",
  "Carne, bovina, cupim, assado": "🥩",
  "Carne, bovina, cupim, cru": "🥩",
  "Carne, bovina, fígado, cru": "🥩",
  "Carne, bovina, fígado, grelhado": "🥩",
  "Carne, bovina, filé mingnon, sem gordura, cru": "🥩",
  "Carne, bovina, filé mingnon, sem gordura, grelhado": "🥩",
  "Carne, bovina, flanco, sem gordura, cozido": "🥩",
  "Carne, bovina, flanco, sem gordura, cru": "🥩",
  "Carne, bovina, fraldinha, com gordura, cozida": "🥩",
  "Carne, bovina, fraldinha, com gordura, crua": "🥩",
  "Carne, bovina, lagarto, cozido": "🥩",
  "Carne, bovina, lagarto, cru": "🥩",
  "Carne, bovina, língua, cozida": "🥩",
  "Carne, bovina, língua, crua": "🥩",
  "Carne, bovina, maminha, crua": "🥩",
  "Carne, bovina, maminha, grelhada": "🥩",
  "Carne, bovina, miolo de alcatra, sem gordura, cru": "🥩",
  "Carne, bovina, miolo de alcatra, sem gordura, grelhado": "🥩",
  "Carne, bovina, músculo, sem gordura, cozido": "🥩",
  "Carne, bovina, músculo, sem gordura, cru": "🥩",
  "Carne, bovina, paleta, com gordura, crua": "🥩",
  "Carne, bovina, paleta, sem gordura, cozida": "🥩",
  "Carne, bovina, paleta, sem gordura, crua": "🥩",
  "Carne, bovina, patinho, sem gordura, cru": "🥩",
  "Carne, bovina, patinho, sem gordura, grelhado": "🥩",
  "Carne, bovina, peito, sem gordura, cozido": "🥩",
  "Carne, bovina, peito, sem gordura, cru": "🥩",
  "Carne, bovina, picanha, com gordura, crua": "🥩",
  "Carne, bovina, picanha, com gordura, grelhada": "🥩",
  "Carne, bovina, picanha, sem gordura, crua": "🥩",
  "Carne, bovina, picanha, sem gordura, grelhada": "🥩",
  "Carne, bovina, seca, cozida": "🥩",
  "Carne, bovina, seca, crua": "🥩",
  "Coxinha de frango, frita": "🍗",
  "Croquete, de carne, cru": "🥩",
  "Croquete, de carne, frito": "🥩",
  "Empada de frango, pré-cozida, assada": "🍗",
  "Empada, de frango, pré-cozida": "🍗",
  "Frango, asa, com pele, crua": "🍗",
  "Frango, caipira, inteiro, com pele, cozido": "🍗",
  "Frango, caipira, inteiro, sem pele, cozido": "🍗",
  "Frango, coração, cru": "🍗",
  "Frango, coração, grelhado": "🍗",
  "Frango, coxa, com pele, assada": "🍗",
  "Frango, coxa, com pele, crua": "🍗",
  "Frango, coxa, sem pele, cozida": "🍗",
  "Frango, coxa, sem pele, crua": "🍗",
  "Frango, fígado, cru": "🍗",
  "Frango, filé, à milanesa": "🍗",
  "Frango, inteiro, com pele, cru": "🍗",
  "Frango, inteiro, sem pele, assado": "🍗",
  "Frango, inteiro, sem pele, cozido": "🍗",
  "Frango, inteiro, sem pele, cru": "🍗",
  "Frango, peito, com pele, assado": "🍗",
  "Frango, peito, com pele, cru": "🍗",
  "Frango, peito, sem pele, cozido": "🍗",
  "Frango, peito, sem pele, cru": "🍗",
  "Frango, peito, sem pele, grelhado": "🍗",
  "Frango, sobrecoxa, com pele, assada": "🍗",
  "Frango, sobrecoxa, com pele, crua": "🍗",
  "Frango, sobrecoxa, sem pele, assada": "🍗",
  "Frango, sobrecoxa, sem pele, crua": "🍗",
  "Hambúrguer, bovino, cru": "🍔",
  "Hambúrguer, bovino, frito": "🍔",
  "Hambúrguer, bovino, grelhado": "🍔",
  "Lingüiça, frango, crua": "🌭",
  "Lingüiça, frango, frita": "🌭",
  "Lingüiça, frango, grelhada": "🌭",
  "Lingüiça, porco, crua": "🌭",
  "Lingüiça, porco, frita": "🌭",
  "Lingüiça, porco, grelhada": "🌭",
  "Mortadela": "🥓",
  "Peru, congelado, assado": "🦃",
  "Peru, congelado, cru": "🦃",
  "Porco, bisteca, crua": "🥓",
  "Porco, bisteca, frita": "🥓",
  "Porco, bisteca, grelhada": "🥓",
  "Porco, costela, assada": "🥓",
  "Porco, costela, crua": "🥓",
  "Porco, lombo, assado": "🥓",
  "Porco, lombo, cru": "🥓",
  "Porco, orelha, salgada, crua": "🥓",
  "Porco, pernil, assado": "🥓",
  "Porco, pernil, cru": "🥓",
  "Porco, rabo, salgada, crua": "🥓",
  "Presunto, com capa de gordura": "🥓",
  "Presunto, sem capa de gordura": "🥓",
  "Quibe, assado": "🥙",
  "Quibe, cru": "🥙",
  "Quibe, frito": "🥙",
  "Salame": "🥓",
  "Toucinho, cru": "🥓",
  "Toucinho, frito": "🥓",

  // Leite e derivados
  "Bebida láctea, pêssego": "🥛",
  "Creme de Leite": "🥛",
  "Iogurte, natural": "🥛",
  "Iogurte, natural, desnatado": "🥛",
  "Iogurte, sabor abacaxi": "🥛",
  "Iogurte, sabor morango": "🥛",
  "Iogurte, sabor pêssego": "🥛",
  "Leite, condensado": "🥛",
  "Leite, de cabra": "🥛",
  "Leite, de vaca, achocolatado": "🥛",
  "Leite, de vaca, desnatado, pó": "🥛",
  "Leite, de vaca, desnatado, UHT": "🥛",
  "Leite, de vaca, integral": "🥛",
  "Leite, de vaca, integral, pó": "🥛",
  "Leite, fermentado": "🥛",
  "Queijo, minas, frescal": "🧀",
  "Queijo, minas, meia cura": "🧀",
  "Queijo, mozarela": "🧀",
  "Queijo, parmesão": "🧀",
  "Queijo, pasteurizado": "🧀",
  "Queijo, petit suisse, morango": "🧀",
  "Queijo, prato": "🧀",
  "Queijo, requeijão, cremoso": "🧀",
  "Queijo, ricota": "🧀",

  // Bebidas (alcoólicas e não alcoólicas)
  "Bebida isotônica, sabores variados": "🧃",
  "Café, infusão 10%": "☕",
  "Cana, aguardente 1": "🥃",
  "Cana, caldo de": "🧃",
  "Cerveja, pilsen 2": "🍺",
  "Chá, erva-doce, infusão 5%": "🫖",
  "Chá, mate, infusão 5%": "🫖",
  "Chá, preto, infusão 5%": "🫖",
  "Coco, água de": "🥥",
  "Refrigerante, tipo água tônica": "🥤",
  "Refrigerante, tipo cola": "🥤",
  "Refrigerante, tipo guaraná": "🥤",
  "Refrigerante, tipo laranja": "🥤",
  "Refrigerante, tipo limão": "🥤",

  // Ovos e derivados
  "Omelete, de queijo": "🍳",
  "Ovo, de codorna, inteiro, cru": "🥚",
  "Ovo, de galinha, clara, cozida/10minutos": "🥚",
  "Ovo, de galinha, gema, cozida/10minutos": "🥚",
  "Ovo, de galinha, inteiro, cozido/10minutos": "🥚",
  "Ovo, de galinha, inteiro, cru": "🥚",
  "Ovo, de galinha, inteiro, frito": "🍳",

  // Produtos açucarados
  "Achocolatado, pó": "🍫",
  "Açúcar, cristal": "🍬",
  "Açúcar, mascavo": "🍬",
  "Açúcar, refinado": "🍬",
  "Chocolate, ao leite": "🍫",
  "Chocolate, ao leite, com castanha do Pará": "🍫",
  "Chocolate, ao leite, dietético": "🍫",
  "Chocolate, meio amargo": "🍫",
  "Cocada branca": "🍬",
  "Doce, de abóbora, cremoso": "🍬",
  "Doce, de leite, cremoso": "🍬",
  "Geléia, mocotó, natural": "🍯",
  "Glicose de milho": "🍬",
  "Maria mole": "🍬",
  "Maria mole, coco queimado": "🍬",
  "Marmelada": "🍯",
  "Mel, de abelha": "🍯",
  "Melado": "🍯",
  "Quindim": "🍮",
  "Rapadura": "🍬",

  // Miscelâneas
  "Café, pó, torrado": "☕",
  "Capuccino, pó": "☕",
  "Fermento em pó, químico": "🧂",
  "Fermento, biológico, levedura, tablete": "🧂",
  "Gelatina, sabores variados, pó": "🍮",
  "Sal, dietético": "🧂",
  "Sal, grosso": "🧂",
  "Shoyu": "🥢",
  "Tempero a base de sal": "🧂",

  // Outros alimentos industrializados
  "Azeitona, preta, conserva": "🫒",
  "Azeitona, verde, conserva": "🫒",
  "Chantilly, spray, com gordura vegetal": "🍦",
  "Leite, de coco": "🥥",
  "Maionese, tradicional com ovos": "🥫",

  // Alimentos preparados
  "Acarajé": "🥙",
  "Arroz carreteiro": "🍚",
  "Baião de dois, arroz e feijão-de-corda": "🍚",
  "Barreado": "🥘",
  "Bife à cavalo, com contra filé": "🥩",
  "Bolinho de arroz": "🍙",
  "Camarão à baiana": "🦐",
  "Charuto, de repolho": "🥬",
  "Cuscuz, de milho, cozido com sal": "🌽",
  "Cuscuz, paulista": "🌽",
  "Cuxá, molho": "🥣",
  "Dobradinha": "🥩",
  "Estrogonofe de carne": "🥘",
  "Estrogonofe de frango": "🥘",
  "Feijão tropeiro mineiro": "🥘",
  "Feijãoada": "🥘",
  "Frango, com açafrão": "🍗",
  "Macarrão, molho bolognesa": "🍝",
  "Maniçoba": "🥘",
  "Quibebe": "🥘",
  "Salada, de legumes, com maionese": "🥗",
  "Salada, de legumes, cozida no vapor": "🥗",
  "Salpicão, de frango": "🥗",
  "Sarapatel": "🥘",
  "Tabule": "🥗",
  "Tacacá": "🥘",
  "Tapioca, com manteiga": "🌮",
  "Tucupi, com pimenta-de-cheiro": "🥣",
  "Vaca atolada": "🥘",
  "Vatapá": "🥘",
  "Virado à paulista": "🥘",
  "Yakisoba": "🍜",

  // Leguminosas e derivados
  "Amendoim, grão, cru": "🥜",
  "Amendoim, torrado, salgado": "🥜",
  "Ervilha, em vagem": "🫘",
  "Ervilha, enlatada, drenada": "🫘",
  "Feijão, carioca, cozido": "🫘",
  "Feijão, carioca, cru": "🫘",
  "Feijão, fradinho, cozido": "🫘",
  "Feijão, fradinho, cru": "🫘",
  "Feijão, jalo, cozido": "🫘",
  "Feijão, jalo, cru": "🫘",
  "Feijão, preto, cozido": "🫘",
  "Feijão, preto, cru": "🫘",
  "Feijão, rajado, cozido": "🫘",
  "Feijão, rajado, cru": "🫘",
  "Feijão, rosinha, cozido": "🫘",
  "Feijão, rosinha, cru": "🫘",
  "Feijão, roxo, cozido": "🫘",
  "Feijão, roxo, cru": "🫘",
  "Grão-de-bico, cru": "🫘",
  "Guandu, cru": "🫘",
  "Lentilha, cozida": "🫘",
  "Lentilha, crua": "🫘",
  "Paçoca, amendoim": "🥜",
  "Pé-de-moleque, amendoim": "🥜",
  "Soja, farinha": "🫘",
  "Soja, extrato solúvel, natural, fluido": "🫘",
  "Soja, extrato solúvel, pó": "🫘",
  "Soja, queijo (tofu)": "🫘",
  "Tremoço, cru": "🫘",
  "Tremoço, em conserva": "🫘",

  // Nozes e sementes
  "Amêndoa, torrada, salgada": "🌰",
  "Castanha-de-caju, torrada, salgada": "🌰",
  "Castanha-do-Brasil, crua": "🌰",
  "Coco, cru": "🥥",
  "Coco,  verde, cru": "🥥",
  "Farinha, de mesocarpo de babaçu, crua": "🌰",
  "Gergelim, semente": "🌰",
  "Linhaça, semente": "🌰",
  "Pinhão, cozido": "🌰",
  "Pupunha, cozida": "🌰",
  "Noz, crua": "🌰"
};

export const getFoodEmoji = (foodName: string): string => {
  // First try to find an exact match in the foodEmojiMap
  const exactMatch = foodEmojiMap[foodName];
  if (exactMatch) {
    return exactMatch;
  }

  // If no exact match, try to find a partial match
  for (const [key, emoji] of Object.entries(foodEmojiMap)) {
    if (foodName.toLowerCase().includes(key.toLowerCase())) {
      return emoji;
    }
  }

  // If no match found, return a default emoji based on the food category
  const lowerFoodName = foodName.toLowerCase();
  if (lowerFoodName.includes("cereal") || lowerFoodName.includes("arroz") || lowerFoodName.includes("aveia")) {
    return "🌾";
  } else if (lowerFoodName.includes("fruta") || lowerFoodName.includes("banana") || lowerFoodName.includes("maçã")) {
    return "🍎";
  } else if (lowerFoodName.includes("vegetal") || lowerFoodName.includes("verdura") || lowerFoodName.includes("legume")) {
    return "🥬";
  } else if (lowerFoodName.includes("carne") || lowerFoodName.includes("frango") || lowerFoodName.includes("peixe")) {
    return "🍖";
  } else if (lowerFoodName.includes("laticínio") || lowerFoodName.includes("leite") || lowerFoodName.includes("queijo")) {
    return "🧀";
  } else if (lowerFoodName.includes("bebida") || lowerFoodName.includes("suco") || lowerFoodName.includes("água")) {
    return "🧃";
  } else {
    return "🍽️"; // Default food emoji
  }
}; 